spring:
  ai:
    zhipuai:
      api-key: [API KEY]
      chat:
        enabled: true
        options:
          model: GLM-4-AirX
          temperature: 0.3
    vectorstore:
      neo4j:
        embedding-dimension: 1024
        index-name: deepReflectionChat
        label: DeepReflectionChat
        initialize-schema: true

  neo4j:
    uri: neo4j://[IP]:7687
    authentication:
      username: neo4j
      password: [PASSWORD]
